<?php
/**
 * BS_Report extension
 * 
 * @category       BS
 * @package        BS_Report
 * @copyright      Copyright (c) 2015
 */
/**
 * Manage edit form tab
 *
 * @category    BS
 * @package     BS_Report
 * @author Bui Phong
 */
class BS_Report_Block_Adminhtml_Supervisor_Edit_Tab_Form extends Mage_Adminhtml_Block_Widget_Form
{

    protected function _prepareLayout()
    {
        $this->setTemplate('bs_report/supervisor/form.phtml');
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    public function getAllReports()
    {
        $myTimezone = new DateTimeZone('Asia/Ho_Chi_Minh');
        $now = new DateTime('now', $myTimezone);
        $hour = intval($now->format('H'));
        if($hour < 12){
            $now->sub(new DateInterval('P1D'));
        }
        $today = $now->format('Y-m-d');
        $start = $today.'00:00:00';
        $end = $today.'23:59:59';

        $currentUser = Mage::getSingleton('admin/session')->getUser();
        $supervisorId = $currentUser->getId();
        $reports = Mage::getModel('bs_report/report')->getCollection();

        if($supervisorId != 1){
            $reports->addFieldToFilter('supervisor_id', $supervisorId);
        }


        $reports->addFieldToFilter('created_at', array('from'=>$start,'to'=>$end, 'date' => true))
            ->setOrder('user_id', 'ASC')
        ;


        if($reports->count()){
            $result = array();
            foreach ($reports as $report) {
                $result[$report->getUserId()][] = $report;
            }

            return $result;
        }

        return false;
    }


    public function buildRatingBlock($id)
    {
        //we get the current rating if any
        $report = Mage::getModel('bs_report/report')->load($id);
        $rateOne = (int)$report->getRateOne();
        $rateTwo = (int)$report->getRateTwo();
        $rateThree = (int)$report->getRateThree();
        $note = $report->getNote();

        $checkOne1 = '';
        $checkOne2 = '';
        $checkOne3 = '';
        $checkOne4 = '';
        $checkOne5 = '';

        if($rateOne == 0){
            $checkOne3 = 'checked="checked"';
        }else {
            switch ($rateOne){
                case 1:
                    $checkOne1 = 'checked="checked"';
                    break;
                case 2:
                    $checkOne2 = 'checked="checked"';
                    break;
                case 3:
                    $checkOne3 = 'checked="checked"';
                    break;
                case 4:
                    $checkOne4 = 'checked="checked"';
                    break;
                case 5:
                    $checkOne5 = 'checked="checked"';
                    break;
            }
        }

        $checkTwo1 = '';
        $checkTwo2 = '';
        $checkTwo3 = '';
        $checkTwo4 = '';
        $checkTwo5 = '';
        if($rateTwo == 0){
            $checkTwo3 = 'checked="checked"';
        }else {
            switch ($rateTwo){
                case 1:
                    $checkTwo1 = 'checked="checked"';
                    break;
                case 2:
                    $checkTwo2 = 'checked="checked"';
                    break;
                case 3:
                    $checkTwo3 = 'checked="checked"';
                    break;
                case 4:
                    $checkTwo4 = 'checked="checked"';
                    break;
                case 5:
                    $checkTwo5 = 'checked="checked"';
                    break;
            }
        }

        $checkThree1 = '';
        $checkThree2 = '';
        $checkThree3 = '';
        $checkThree4 = '';
        $checkThree5 = '';
        if($rateThree == 0){
            $checkThree3 = 'checked="checked"';
        }else {
            switch ($rateThree){
                case 1:
                    $checkThree1 = 'checked="checked"';
                    break;
                case 2:
                    $checkThree2 = 'checked="checked"';
                    break;
                case 3:
                    $checkThree3 = 'checked="checked"';
                    break;
                case 4:
                    $checkThree4 = 'checked="checked"';
                    break;
                case 5:
                    $checkThree5 = 'checked="checked"';
                    break;
            }
        }


        $html = '<div class="fieldset ratings">
            <h4>How do you rate this task?</h4>
            <span id="input-message-box"></span>
            <table id="product-review-table" class="data-table review-summary-table ratings">
                <colgroup><col width="1">
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                </colgroup><thead>
                <tr class="first last">
                    <th>&nbsp;</th>
                    <th>
                        <div class="rating-box">
                            <span style="width:20%;" class="rating nobr"></span>
                        </div>
                    </th>
                    <th>
                        <div class="rating-box">
                            <span style="width:40%;" class="rating nobr"></span>
                        </div>
                    </th>
                    <th>
                        <div class="rating-box">
                            <span style="width:60%;" class="rating nobr"></span>
                        </div>
                    </th>
                    <th>
                        <div class="rating-box">
                            <span style="width:80%;" class="rating nobr"></span>
                        </div>
                    </th>
                    <th>
                        <div class="rating-box">
        
                            <span style="width:100%;" class="rating nobr"></span>
                        </div>
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr class="first odd">
                    <th>Quantity</th>
                    <td class="value"><label><input type="radio" '.$checkOne1.' class="radio" value="1" name="rate_one['.$id.']"></label></td>
                    <td class="value"><label><input type="radio" '.$checkOne2.' class="radio" value="2" name="rate_one['.$id.']"></label></td>
                    <td class="value"><label><input type="radio" '.$checkOne3.' class="radio" value="3" name="rate_one['.$id.']"></label></td>
                    <td class="value"><label><input type="radio" '.$checkOne4.' class="radio" value="4" name="rate_one['.$id.']"></label></td>
                    <td class="value"><label><input type="radio" '.$checkOne5.' class="radio" value="5" name="rate_one['.$id.']"></label></td>
                </tr>
                <tr class="even">
                    <th>Quality</th>
                    <td class="value"><label><input type="radio" '.$checkTwo1.' class="radio" value="1" name="rate_two['.$id.']"></label></td>
                    <td class="value"><label><input type="radio" '.$checkTwo2.' class="radio" value="2" name="rate_two['.$id.']"></label></td>
                    <td class="value"><label><input type="radio" '.$checkTwo3.' class="radio" value="3" name="rate_two['.$id.']"></label></td>
                    <td class="value"><label><input type="radio" '.$checkTwo4.' class="radio" value="4" name="rate_two['.$id.']"></label></td>
                    <td class="value"><label><input type="radio" '.$checkTwo5.' class="radio" value="5" name="rate_two['.$id.']"></label></td>
                </tr>
                <tr class="odd">
                    <th>Attitude</th>
                    <td class="value"><label><input type="radio" '.$checkThree1.' class="radio" value="1" name="rate_three['.$id.']"></label></td>
                    <td class="value"><label><input type="radio" '.$checkThree2.' class="radio" value="2" name="rate_three['.$id.']"></label></td>
                    <td class="value"><label><input type="radio" '.$checkThree3.' class="radio" value="3" name="rate_three['.$id.']"></label></td>
                    <td class="value"><label><input type="radio" '.$checkThree4.' class="radio" value="4" name="rate_three['.$id.']"></label></td>
                    <td class="value"><label><input type="radio" '.$checkThree5.' class="radio" value="5" name="rate_three['.$id.']"></label></td>
                </tr>
                <tr class="last even">
                    <th>Note</th>
                    <td colspan="5" class="value">
                        <div class="input-box">
                            <input type="text" value="'.$note.'" class="input-text"  name="note['.$id.']">
                        </div>
                    </td>
                </tr>
        
                </tbody>
            </table>
        
        
        </div>';

        return $html;
    }


}
