<?php $_restrict = $this->getRestrictByRegion() ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Role by Region') ?></h4>
    </div>
    <fieldset>
        <span class="field-row">
            <label for="restrict_by_region"><?php echo $this->__('Restrict Role by Region?') ?></label>
            <select id="restrict_by_region" name="restrict_by_region" class="select">
                <option value="0" <?php if (!$_restrict) echo 'selected="selected"' ?>><?php echo $this->__('No') ?></option>
                <option value="1" <?php if ($_restrict) echo 'selected="selected"' ?>><?php echo $this->__('Yes') ?></option>
            </select>
        </span>
    </fieldset>
</div>