<?php
/**
 * BS_Report extension
 * 
 * @category       BS
 * @package        BS_Report
 * @copyright      Copyright (c) 2015
 */
/**
 * Individual Report edit form tab
 *
 * @category    BS
 * @package     BS_Report
 * @author Bui Phong
 */
class BS_Report_Block_Adminhtml_Report_Edit_Tab_Form extends Mage_Adminhtml_Block_Widget_Form
{
    protected function _prepareLayout()
    {
        if ($this->getRequest()->getParam('v2', false)) {
            $this->setTemplate('bs_report/form.phtml');
        }

        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    public function getFieldId(){
        return 'individual_report';
    }

    public function getAddButtonId(){
        return 'add_new_row';
    }

    public function getTaskSelectHtml()
    {
        $currentUser = Mage::getSingleton('admin/session')->getUser();
        $isSouth = $currentUser->getSouthern();

        $select = $this->getLayout()->createBlock('adminhtml/html_select')
            ->setData(array(
                'id' => $this->getFieldId().'_select_{{id}}',
                'class' => 'select select-task'
            ))
            ->setName('report[{{id}}][tctask_id]')
            ->setOptions(Mage::getModel('bs_report/report_attribute_source_tasks')->getAllOptions(false, false, false, $isSouth));

        return $select->getHtml();
    }

    public function getSupervisorSelectHtml()
    {
        $select = $this->getLayout()->createBlock('adminhtml/html_select')
            ->setData(array(
                'id' => $this->getFieldId().'_select_supervisor_{{id}}',
                'class' => 'select select-supervisor'
            ))
            ->setName('report[{{id}}][supervisor_id]')
            ->setOptions(Mage::getModel('bs_report/report_attribute_source_supervisor')->getAllOptions(false));

        return $select->getHtml();
    }

    public function getStatusSelectHtml()
    {
        $select = $this->getLayout()->createBlock('adminhtml/html_select')
            ->setData(array(
                'id' => $this->getFieldId().'_select_status_{{id}}',
                'class' => 'select select-status'
            ))
            ->setName('report[{{id}}][task_status]')
            ->setOptions(Mage::getModel('bs_report/report_attribute_source_taskstatus')->getAllOptions(true));

        return $select->getHtml();
    }

    /**
     * prepare the form
     *
     * @access protected
     * @return BS_Report_Block_Adminhtml_Report_Edit_Tab_Form
     * @author Bui Phong
     */
    protected function _prepareForm()
    {
        $form = new Varien_Data_Form();
        $form->setHtmlIdPrefix('report_');
        $form->setFieldNameSuffix('report');
        $this->setForm($form);
        $fieldset = $form->addFieldset(
            'report_form',
            array('legend' => Mage::helper('bs_report')->__('Individual Report.'))
        );

        $currentUser = Mage::getSingleton('admin/session')->getUser();
        $isSouth = $currentUser->getSouthern();

        $tasks = $this->getRequest()->getParam('report', false);

        if(!$tasks){
            $fieldset->addField(
                'tctask_id',
                'select',
                array(
                    'label' => Mage::helper('bs_report')->__('Task'),
                    'name'  => 'tctask_id',
                    'values'=> Mage::getModel('bs_report/report_attribute_source_tasks')->getAllOptions(false,false, false, $isSouth),

                )
            );

            $fieldset->addField(
                'supervisor_id',
                'select',
                array(
                    'label' => Mage::helper('bs_report')->__('Supervisor'),
                    'name'  => 'supervisor_id',
                    'values'=> Mage::getModel('bs_report/report_attribute_source_supervisor')->getAllOptions(false),

                )
            );
            $fieldset->addField(
                'detail',
                'textarea',
                array(
                    'label' => Mage::helper('bs_report')->__('Detail'),
                    'name'  => 'detail',

                )
            );

            $fieldset->addField(
                'task_qty',
                'text',
                array(
                    'label' => Mage::helper('bs_report')->__('Quantity'),
                    'name'  => 'task_qty',
                    'note'	=> $this->__('Number of work done'),

                )
            );

            $fieldset->addField(
                'task_time',
                'text',
                array(
                    'label' => Mage::helper('bs_report')->__('Doing time'),
                    'name'  => 'task_time',
                    'note'	=> $this->__('Minutes'),

                )
            );

            $fieldset->addField(
                'task_status',
                'select',
                array(
                    'label' => Mage::helper('bs_report')->__('Status'),
                    'name'  => 'task_status',

                    'values'=> Mage::getModel('bs_report/report_attribute_source_taskstatus')->getAllOptions(true),
                )
            );

        }



        $check = $this->helper('bs_report')->checkSupervisor();
        if($check){

            if($tasks){
                $fieldset->addField(
                    'task_ids',
                    'text',
                    array(
                        'label' => Mage::helper('bs_report')->__('Tasks'),
                        'name'  => 'task_ids',
                        'readonly'  => true

                    )
                );
            }


            $fieldset->addField(
                'rate_one',
                'select',
                array(
                    'label' => Mage::helper('bs_report')->__('Đ/g khối lượng công việc'),
                    'name'  => 'rate_one',

                    'values'=> Mage::getModel('bs_report/report_attribute_source_rateone')->getAllOptions(true),
                )
            );

            $fieldset->addField(
                'rate_two',
                'select',
                array(
                    'label' => Mage::helper('bs_report')->__('Đ/g chất lượng công việc'),
                    'name'  => 'rate_two',

                    'values'=> Mage::getModel('bs_report/report_attribute_source_ratetwo')->getAllOptions(true),
                )
            );

            $fieldset->addField(
                'rate_three',
                'select',
                array(
                    'label' => Mage::helper('bs_report')->__('Đ/g Ý thức tổ chức kỷ luật'),
                    'name'  => 'rate_three',

                    'values'=> Mage::getModel('bs_report/report_attribute_source_ratethree')->getAllOptions(true),
                )
            );
        }



        /*$fieldset->addField(
            'user_id',
            'text',
            array(
                'label' => Mage::helper('bs_report')->__('User Id'),
                'name'  => 'user_id',

           )
        );*/



        /*$fieldset->addField(
            'complete',
            'select',
            array(
                'label' => Mage::helper('bs_report')->__('Complete (%)'),
                'name'  => 'complete',

            'values'=> Mage::getModel('bs_report/report_attribute_source_complete')->getAllOptions(true),
           )
        );

        $fieldset->addField(
            'expected_date',
            'date',
            array(
                'label' => Mage::helper('bs_report')->__('Expected Complete Date'),
                'name'  => 'expected_date',

            'image' => $this->getSkinUrl('images/grid-cal.gif'),
            'format'  => Mage::app()->getLocale()->getDateFormat(Mage_Core_Model_Locale::FORMAT_TYPE_SHORT),
           )
        );*/

        /*$fieldset->addField(
            'note',
            'textarea',
            array(
                'label' => Mage::helper('bs_report')->__('Note'),
                'name'  => 'note',

           )
        );*/
        /*$fieldset->addField(
            'status',
            'select',
            array(
                'label'  => Mage::helper('bs_report')->__('Status'),
                'name'   => 'status',
                'values' => array(
                    array(
                        'value' => 1,
                        'label' => Mage::helper('bs_report')->__('Enabled'),
                    ),
                    array(
                        'value' => 0,
                        'label' => Mage::helper('bs_report')->__('Disabled'),
                    ),
                ),
            )
        );*/
        $formValues = Mage::registry('current_report')->getDefaultValues();
        if (!is_array($formValues)) {
            $formValues = array();
        }
        if (Mage::getSingleton('adminhtml/session')->getReportData()) {
            $formValues = array_merge($formValues, Mage::getSingleton('adminhtml/session')->getReportData());
            Mage::getSingleton('adminhtml/session')->setReportData(null);
        } elseif (Mage::registry('current_report')) {
            $formValues = array_merge($formValues, Mage::registry('current_report')->getData());
        }

        if($tasks){
            $tasks = implode(",", $tasks);
            $formValues = array_merge($formValues, array('task_ids'=>$tasks));
        }

        $form->setValues($formValues);

        $this->setChild('form_after', $this->getLayout()->createBlock('adminhtml/widget_form_element_dependence')
            ->addFieldMap("report_tctask_id", 'tctask_id')
            ->addFieldMap("report_supervisor_id", 'supervisor_id')
            ->addFieldDependence('supervisor_id', 'tctask_id', array('51','52','53','54','55'))
        );
        return parent::_prepareForm();
    }
}
