<?php
/**
 * BS_KST extension
 * 
 * @category       BS
 * @package        BS_KST
 * @copyright      Copyright (c) 2015
 */
/**
 * Item admin grid block
 *
 * @category    BS
 * @package     BS_KST
 * @author Bui Phong
 */
class BS_KST_Block_Adminhtml_Kstitem_Grid extends Mage_Adminhtml_Block_Widget_Grid
{
    /**
     * constructor
     *
     * @access public
     * @author Bui Phong
     */
    public function __construct()
    {
        parent::__construct();
        $this->setId('kstitemGrid');
        $this->setDefaultSort('entity_id');
        $this->setDefaultDir('DESC');
        $this->setSaveParametersInSession(true);
        $this->setUseAjax(true);
    }

    protected function _afterToHtml($html)
    {
        $html .= "<script>
                    if($('kstitemGrid_filter_curriculum_id') != undefined){
                        $('kstitemGrid_filter_curriculum_id').observe('change', function(){
                            $('kstitemGrid_filter_kstsubject_id').selectedIndex = 0;
                            kstitemGridJsObject.doFilter();
                        });
                    }

                    if($('kstitemGrid_filter_kstsubject_id') != undefined){
                        $('kstitemGrid_filter_kstsubject_id').observe('change', function(){
                            kstitemGridJsObject.doFilter();
                        });
                    }


                </script>";
        return parent::_afterToHtml($html); // TODO: Change the autogenerated stub
    }

    /**
     * prepare collection
     *
     * @access protected
     * @return BS_KST_Block_Adminhtml_Kstitem_Grid
     * @author Bui Phong
     */
    protected function _prepareCollection()
    {
        $collection = Mage::getModel('bs_kst/kstitem')
            ->getCollection();

        //$requestData = Mage::helper('adminhtml')->prepareFilterString($this->getRequest()->getParam('filter'));

        //$collection->getSelect()->joinLeft(array('sub'=>$collection->getTable('bs_kst/kstsubject')),'kstsubject_id = sub.entity_id','sub.curriculum_id AS curriculum_id');

        $collection->addFilterToMap('entity_id','main_table.entity_id');

        $this->setCollection($collection);
        return parent::_prepareCollection();
    }

    /**
     * prepare grid collection
     *
     * @access protected
     * @return BS_KST_Block_Adminhtml_Kstitem_Grid
     * @author Bui Phong
     */
    protected function _prepareColumns()
    {
        $requestData = Mage::helper('adminhtml')->prepareFilterString($this->getRequest()->getParam('filter'));

        $subjectId = 0;
        $curriculumId = 0;

        if(isset($requestData['curriculum_id']) && (int)$requestData['curriculum_id'] > 0){
            $curriculumId = (int)$requestData['curriculum_id'];

        }

        $this->addColumn(
            'entity_id',
            array(
                'header' => Mage::helper('bs_kst')->__('Id'),
                'index'  => 'entity_id',
                'type'   => 'number'
            )
        );

        $currs = Mage::getResourceModel('bs_traininglist/curriculum_collection')->addAttributeToFilter('c_code',array(array('like'=>'%KST%'), array('like'=>'%CRS%')));
        if($curriculumId > 0){
            //$currs->addAttributeToFilter('entity_id', $curriculumId);
        }

        $currs = $currs->toOptionCodeHash();

        $this->addColumn(
            'curriculum_id',
            array(
                'header'    => Mage::helper('bs_kst')->__('Curriculum'),
                'index'     => 'curriculum_id',
                'type'      => 'options',
                'options'   => $currs,
            )
        );


        $subs = Mage::getResourceModel('bs_kst/kstsubject_collection');

        if($curriculumId > 0){
            $subs->addFieldToFilter('curriculum_id', $curriculumId);
        }
        $subs = $subs->toOptionHash();


        $this->addColumn(
            'kstsubject_id',
            array(
                'header'    => Mage::helper('bs_kst')->__('Subject'),
                'index'     => 'kstsubject_id',
                'type'      => 'options',
                'options'   => $subs,
                'renderer'  => 'bs_kst/adminhtml_helper_column_renderer_parent',
                'params'    => array(
                    'id'    => 'getKstsubjectId'
                ),
                'base_link' => 'adminhtml/kst_kstsubject/edit'
            )
        );
        $this->addColumn(
            'name',
            array(
                'header'    => Mage::helper('bs_kst')->__('Name'),
                'align'     => 'left',
                'index'     => 'name',
            )
        );
        

        $this->addColumn(
            'ref',
            array(
                'header' => Mage::helper('bs_kst')->__('Reference Doc'),
                'index'  => 'ref',
                'type'=> 'text',

            )
        );
        $this->addColumn(
            'taskcode',
            array(
                'header' => Mage::helper('bs_kst')->__('Task Code'),
                'index'  => 'taskcode',
                'type'=> 'text',

            )
        );
        $this->addColumn(
            'taskcat',
            array(
                'header' => Mage::helper('bs_kst')->__('Task Cat'),
                'index'  => 'taskcat',
                'type'=> 'text',

            )
        );
        $this->addColumn(
            'applicable_for',
            array(
                'header' => Mage::helper('bs_kst')->__('Applicable For'),
                'index'  => 'applicable_for',
                'type'=> 'text',

            )
        );
        $this->addColumn(
            'position',
            array(
                'header' => Mage::helper('bs_kst')->__('Position'),
                'index'  => 'position',
                'type'=> 'number',

            )
        );

        $this->addColumn(
            'action',
            array(
                'header'  =>  Mage::helper('bs_kst')->__('Action'),
                'width'   => '100',
                'type'    => 'action',
                'getter'  => 'getId',
                'actions' => array(
                    array(
                        'caption' => Mage::helper('bs_kst')->__('Edit'),
                        'url'     => array('base'=> '*/*/edit'),
                        'field'   => 'id'
                    )
                ),
                'filter'    => false,
                'is_system' => true,
                'sortable'  => false,
            )
        );
        $this->addExportType('*/*/exportCsv', Mage::helper('bs_kst')->__('CSV'));
        $this->addExportType('*/*/exportExcel', Mage::helper('bs_kst')->__('Excel'));
        $this->addExportType('*/*/exportXml', Mage::helper('bs_kst')->__('XML'));
        return parent::_prepareColumns();
    }

    /**
     * prepare mass action
     *
     * @access protected
     * @return BS_KST_Block_Adminhtml_Kstitem_Grid
     * @author Bui Phong
     */
    protected function _prepareMassaction()
    {
        $this->setMassactionIdField('entity_id');
        $this->getMassactionBlock()->setFormFieldName('kstitem');

        $isAllowedEdit = Mage::getSingleton('admin/session')->isAllowed("bs_kst/kstitem/edit");
        $isAllowedDelete = Mage::getSingleton('admin/session')->isAllowed("bs_kst/kstitem/delete");

        if($isAllowedDelete){
            $this->getMassactionBlock()->addItem(
                'delete',
                array(
                    'label'=> Mage::helper('bs_kst')->__('Delete'),
                    'url'  => $this->getUrl('*/*/massDelete'),
                    'confirm'  => Mage::helper('bs_kst')->__('Are you sure?')
                )
            );
        }

        if($isAllowedEdit){




        $values = Mage::getResourceModel('bs_kst/kstsubject_collection')->toOptionHash();
        $values = array_reverse($values, true);
        $values[''] = '';
        $values = array_reverse($values, true);
        $this->getMassactionBlock()->addItem(
            'kstsubject_id',
            array(
                'label'      => Mage::helper('bs_kst')->__('Change Subject'),
                'url'        => $this->getUrl('*/*/massKstsubjectId', array('_current'=>true)),
                'additional' => array(
                    'flag_kstsubject_id' => array(
                        'name'   => 'flag_kstsubject_id',
                        'type'   => 'select',
                        'class'  => 'required-entry',
                        'label'  => Mage::helper('bs_kst')->__('Subject'),
                        'values' => $values
                    )
                )
            )
        );

            $this->getMassactionBlock()->addItem(
                'changecase',
                array(
                    'label'      => Mage::helper('bs_kst')->__('Uppercase'),
                    'url'        => $this->getUrl('*/*/massChangeCase', array('_current'=>true)),
                    'additional' => array(
                        'changecase' => array(
                            'name'   => 'changecase',
                            'type'   => 'select',
                            'class'  => 'required-entry',
                            'label'  => Mage::helper('bs_kst')->__('Subject'),
                            'values' => array(
                                'ref'   => 'Ref Doc',
                                'code'  => 'Task Code',
                                'cat'   => 'Task Cat'
                            )
                        )
                    )
                )
            );
        }



        return $this;
    }

    /**
     * get the row url
     *
     * @access public
     * @param BS_KST_Model_Kstitem
     * @return string
     * @author Bui Phong
     */
    public function getRowUrl($row)
    {
        return $this->getUrl('*/*/edit', array('id' => $row->getId()));
    }

    /**
     * get the grid url
     *
     * @access public
     * @return string
     * @author Bui Phong
     */
    public function getGridUrl()
    {
        return $this->getUrl('*/*/grid', array('_current'=>true));
    }

    /**
     * after collection load
     *
     * @access protected
     * @return BS_KST_Block_Adminhtml_Kstitem_Grid
     * @author Bui Phong
     */
    protected function _afterLoadCollection()
    {
        $this->getCollection()->walk('afterLoad');
        parent::_afterLoadCollection();
    }

}
