INSERT INTO `customer_group` (`customer_group_code`,`tax_class_id`,`customer_group_code_vi`,`customer_group_name`,`customer_group_name_vi`) VALUES
('KH',3,'KH','Ban Kế hoạch','Ban Kế hoạch'),
('KT&CNTT',3,'KT&CNTT','Ban Kỹ thuật và công nghệ thông tin','Ban Kỹ thuật và công nghệ thông tin'),
('CUVT',3,'CUVT','Ban Cung ứng Vật tư','Ban Cung ứng Vật tư'),
('DBCL',3,'DBCL','Ban Đảm bảo Chất lượng','Ban Đảm bảo Chất lượng'),
('PTKD',3,'PTKD','Ban Phát triển kinh doanh','Ban Phát triển kinh doanh'),
('QLHG',3,'QLHG','Ban Quản lý dự án Hangar','Ban Quản lý dự án Hangar'),
('PCHD',3,'PCHD','Phòng Pháp chế và Hợp đồng','Phòng Pháp chế và Hợp đồng'),
('VP',3,'VP','Văn phòng','Văn phòng'),
('CNHCM',3,'CNHCM','Chi nhánh Thành phố Hồ Chí Minh','Chi nhánh Thành phố Hồ Chí Minh'),
('CNDN',3,'CNDN','Chi nhánh  Thành phố Đà nẵng','Chi nhánh  Thành phố Đà nẵng'),
('DHBD',3,'DHBD','Trung tâm Điều hành Bảo dưỡng','Trung tâm Điều hành Bảo dưỡng'),
('NTHN',3,'NTHN','Trung tâm Bảo dưỡng Nội trường Hà Nội','Trung tâm Bảo dưỡng Nội trường Hà Nội'),
('NTHCM',3,'NTHCM','Trung tâm bảo dưỡng Nội trường Hồ Chí Minh','Trung tâm bảo dưỡng Nội trường Hồ Chí Minh'),
('NgTHN',3,'NgTHN','Trung tâm Bảo dưỡng Ngoại trường Hà Nội','Trung tâm Bảo dưỡng Ngoại trường Hà Nội'),
('NgTHCM',3,'NgTHCM','Trung tâm bảo dưỡng Ngoại trường Hồ Chí Minh','Trung tâm bảo dưỡng Ngoại trường Hồ Chí Minh'),
('NgTDN',3,'NgTDN','Trung tâm bảo dưỡng Ngoại trường Đà Nẵng','Trung tâm bảo dưỡng Ngoại trường Đà Nẵng'),
('TBHN',3,'TBHN','Trung tâm Bảo dưỡng Thiết bị Hà Nội','Trung tâm Bảo dưỡng Thiết bị Hà Nội'),
('TBHCM',3,'TBHCM','Trung tâm bảo dưỡng Thiết bị Hồ Chí Minh','Trung tâm bảo dưỡng Thiết bị Hồ Chí Minh'),
('NTh',3,'NTh','Trung tâm Bảo dưỡng Nội thất','Trung tâm Bảo dưỡng Nội thất'),
('TC',3,'TTDT','Trung tâm Đào tạo','Trung tâm Đào tạo'),
('D&DT',3,'D&DT','Văn phòng Đảng - Đoàn thể','Văn phòng Đảng - Đoàn thể');
